version: '3.4'
services:
  backend:  
    container_name: backend.app
    image: ${IMAGE_APP_TAG}
    build: .
    restart: unless-stopped
    ports: 
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - adminer

  db:
    container_name: backend.db
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PSQL_HOST}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - "5432"

  adminer:
    container_name: backend.adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=backend.db
    ports:
      - 8090:8080
    depends_on:
      - db
