version: '3.4'
services:
  backend:  
    container_name: backend.app
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - '5000:5000'
    volumes:
      - .:/backend/src
    env_file:
      - .env
  
  db:
    container_name: backend.db
    image: postgres:10.5
    environment:
      - POSTGRES_DB=${PSQL_HOST}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"

  adminer:
    container_name: backend.adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mymis.db
    ports:
      - 8090:8080
    depends_on:
      - db
