version: '3.4'
services:
  backend:
    image: ${IMAGE_APP_TAG}
      build: ./backend/
      environment:
        - INTERNAL_API_URL=https://sam-sla.net/
      ports:
          - "5000:5000"
  
  db:
    container_name: site.db
    image: postgres:10.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  adminer:
    container_name: site.adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mymis.db
    ports:
      - 8090:8080
    depends_on:
      - db
