server:
  error:
    include-message: always
  port: 8090
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILE:psql}
  application:
    name: site-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: site-backend
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  level:
    org.springframework.security: DEBUG
  datasource:
    autoCommit: false
  mvc:
    dispatch-options-request: true

logging:
  file:
    path:
      .
    name:
      logs.log
  level:
    org:
      keycloak: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: psql
  datasource:
    url: jdbc:postgresql://localhost:5435/site
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: update.sql
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: public
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /api/v1/docs

---
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5435/test
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      hbm2ddl:
        auto:
          create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /api/v1/docs
