server:
  error:
    include-message: always
  port: 8090
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILE:psql}
  application:
    name: site-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: site-backend
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  level:
    org.springframework.security: DEBUG

  mvc:
    dispatch-options-request: true

logging:
  level:
    org:
      keycloak: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: mem
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:dcbapp
    username: admin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /api/v1/docs

---
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: psql
  datasource:
    url: jdbc:postgresql://localhost:5435/site
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /api/v1/docs
