name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mvn -B clean package -D skipTests
        run: mvn -B clean package -D skipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/site-backend:latest

      - name: Connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/site-backend:latest
            docker rm -f site-backend
            docker run -d --name site-backend -p 8090:8090  ${{ secrets.DOCKER_HUB_USERNAME }}/site-backend